-- ============================================================
-- education 슬라이스 코어 (education-service 흡수 이관)
--
-- 원본: education-service V1__education_schema.sql. 테이블은 자체 education 스키마를
-- 유지한다 — 엔티티가 @Table(schema = "education") 로 명시 매핑하므로 opslab 기본
-- 스키마와 섞이지 않는다(도메인 데이터 경계가 스키마로 남는다).
--
-- ★ 원본의 education.outbox_events 는 이관하지 않는다 — operation 은 opslab.outbox_events
--   단일 Outbox 를 이미 소유하고(V2), shared-common 폴러의 네이티브 쿼리가 그 스키마를
--   하드코딩한다. education 발행(CoursePublished)도 같은 테이블로 들어간다.
--   구 DB(lemuel_education)의 outbox 행은 이미 발행 완료된 이력이라 복사 대상이 아니다.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS education;

CREATE TABLE education.education_courses (
    id UUID PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT education_courses_status_ck CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN', 'CLOSED'))
);

CREATE TABLE education.education_lessons (
    id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES education.education_courses(id),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    sequence INTEGER NOT NULL,
    content_type VARCHAR(30) NOT NULL,
    content_ref TEXT NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT education_lessons_sequence_uk UNIQUE (course_id, sequence),
    CONSTRAINT education_lessons_status_ck CHECK (status IN ('ACTIVE', 'HIDDEN'))
);

CREATE INDEX education_courses_status_idx ON education.education_courses(status, updated_at DESC);
CREATE INDEX education_lessons_course_idx ON education.education_lessons(course_id, sequence);

CREATE TABLE education.education_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id UUID NOT NULL,
    actor VARCHAR(100) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX education_audit_resource_idx ON education.education_audit_logs(resource_type, resource_id, created_at DESC);
